-- CreateEnum
CREATE TYPE "AI_TONE" AS ENUM ('PROFESSIONAL', 'FRIENDLY', 'CASUAL', 'ENTHUSIASTIC');

-- CreateEnum
CREATE TYPE "AI_RESPONSE_STYLE" AS ENUM ('CONCISE', 'DETAILED', 'BALANCED');

-- AlterTable
ALTER TABLE "Listener" ADD COLUMN     "aiMaxLength" INTEGER DEFAULT 2,
ADD COLUMN     "aiResponseStyle" "AI_RESPONSE_STYLE" DEFAULT 'BALANCED',
ADD COLUMN     "aiTone" "AI_TONE" DEFAULT 'FRIENDLY',
ADD COLUMN     "aiUseEmojis" BOOLEAN DEFAULT true;
